---
  - name: 'Update APT package cache'
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: 'Upgrade APT to the latest packages'
    apt:
      upgrade: safe
    register: apt_upgrade

  - name: 'Reboot'
    ansible.builtin.reboot:
    when: apt_upgrade.changed
